# Generated by Django 5.2.13 on 2026-05-10 02:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission_title', models.CharField(default='Our Mission', max_length=200)),
                ('mission_content', models.TextField()),
                ('vision_title', models.CharField(default='Our Vision', max_length=200)),
                ('vision_content', models.TextField()),
                ('commitment_title', models.CharField(default='We are committed for better service', max_length=200)),
                ('commitment_description', models.TextField(blank=True)),
                ('stat1_value', models.PositiveIntegerField(default=0)),
                ('stat1_label', models.CharField(default='Success Treatment', max_length=100)),
                ('stat2_value', models.PositiveIntegerField(default=0)),
                ('stat2_label', models.CharField(default='Happy Clients', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='shared.media')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
